import { NextResponse } from "next/server";
import { buildReport, reportToCsv, REPORT_TYPES, type ReportType } from "@/lib/reports";
import { companyFromRequest, loadSetting, saveSetting } from "@/lib/company";
import { sendEmail, emailConfigured } from "@/lib/notify";

export const runtime = "nodejs";

/** A saved auto-email schedule (stored per company in app_settings). */
export interface ReportSchedule {
  id: string;
  type: ReportType;
  cadence: "daily" | "weekly" | "monthly";
  recipients: string[];
}

const validType = (t: string | null): t is ReportType =>
  !!t && REPORT_TYPES.some((r) => r.type === t);

export async function GET(request: Request) {
  const url = new URL(request.url);
  const companyId = await companyFromRequest(request);

  if (url.searchParams.get("schedules")) {
    const { value } = await loadSetting<ReportSchedule[]>(companyId, "report_schedules");
    return NextResponse.json({ schedules: value ?? [], emailConfigured: emailConfigured() });
  }

  const type = url.searchParams.get("type");
  if (!validType(type)) return NextResponse.json({ error: "Unknown report type." }, { status: 400 });
  try {
    const report = await buildReport(companyId, type, {
      from: url.searchParams.get("from") ?? undefined,
      to: url.searchParams.get("to") ?? undefined,
      van: url.searchParams.get("van") ?? undefined,
      driver: url.searchParams.get("driver") ?? undefined,
    });
    return NextResponse.json({ report });
  } catch (e) {
    return NextResponse.json(
      { error: e instanceof Error ? e.message : "Report failed" },
      { status: 500 }
    );
  }
}

/** POST: send a report by email right now (CSV attached). */
export async function POST(request: Request) {
  const body = (await request.json().catch(() => ({}))) as {
    type?: string;
    from?: string;
    to?: string;
    van?: string;
    driver?: string;
    recipients?: string[];
  };
  if (!validType(body.type ?? null)) {
    return NextResponse.json({ error: "Unknown report type." }, { status: 400 });
  }
  const recipients = (body.recipients ?? []).map((r) => r.trim()).filter(Boolean);
  if (recipients.length === 0) {
    return NextResponse.json({ error: "At least one recipient email is required." }, { status: 400 });
  }
  if (!emailConfigured()) {
    return NextResponse.json({ error: "Email isn't configured yet (RESEND_API_KEY)." }, { status: 503 });
  }

  const companyId = await companyFromRequest(request);
  const report = await buildReport(companyId, body.type as ReportType, {
    from: body.from,
    to: body.to,
    van: body.van,
    driver: body.driver,
  });
  const csv = reportToCsv(report);
  const stamp = new Date().toISOString().slice(0, 10);
  await sendEmail(
    recipients,
    `${report.title} — ${report.rangeLabel}`,
    `Attached: ${report.title} (${report.rangeLabel}), ${report.rows.length} rows.\n\nGenerated by Last Mile Assist.`,
    [
      {
        filename: `${report.type}-${stamp}.csv`,
        content: Buffer.from(csv, "utf8").toString("base64"),
      },
    ]
  );
  return NextResponse.json({ ok: true, sent: recipients.length, rows: report.rows.length });
}

/** PUT: save the auto-email schedules for this company. */
export async function PUT(request: Request) {
  const body = (await request.json().catch(() => ({}))) as { schedules?: ReportSchedule[] };
  if (!Array.isArray(body.schedules)) {
    return NextResponse.json({ error: "Invalid schedules." }, { status: 400 });
  }
  for (const s of body.schedules) {
    if (!validType(s.type) || !["daily", "weekly", "monthly"].includes(s.cadence)) {
      return NextResponse.json({ error: "Invalid schedule entry." }, { status: 400 });
    }
    s.recipients = (s.recipients ?? []).map((r) => r.trim()).filter(Boolean);
    if (s.recipients.length === 0) {
      return NextResponse.json({ error: "Every schedule needs at least one recipient." }, { status: 400 });
    }
  }
  try {
    await saveSetting(await companyFromRequest(request), "report_schedules", body.schedules);
  } catch (e) {
    return NextResponse.json(
      { error: e instanceof Error ? e.message : "Save failed" },
      { status: 500 }
    );
  }
  return NextResponse.json({ ok: true });
}
